version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: github.com/aws/aws-sdk-go-v2
    versions:
    - 1.3.0
    - 1.3.1
    - 1.3.2
    - 1.3.3
  - dependency-name: github.com/aws/aws-sdk-go-v2/config
    versions:
    - 1.1.1
    - 1.1.3
    - 1.1.4
    - 1.1.5
  - dependency-name: github.com/aws/aws-sdk-go-v2/service/cloudwatchlogs
    versions:
    - 1.2.0
    - 1.2.1
  - dependency-name: github.com/aws/aws-sdk-go
    versions:
    - 1.37.10
    - 1.37.15
    - 1.37.20
    - 1.37.24
